### ISSUE TITLE
Upgrade to react-router v1.0

### ISSUE THREAD

**Issue by sergonius** [tutsplus/build-a-microblogging-app-with-react-and-flux#2]
It's quite a big change, and a recent one as well, would make sense to update it ASAP.

**Comment by adamarthurryan** [comment]
Hi @sergonius, have you checked what changes to the source code would be required to upgrade to 1.0?

**Comment by sergonius** [comment]
Yeah, I am actually making the changes as I go with the tutorial.
What I've changed so far:
- added in `IndexRoute` into main.js
- removed params from links, since those don't exist anymore
- removed `RouteHandler` in favour of `{item.props.children}`
- Routes also don't have names anymore
- I also had to manually install the `history` package and use it so the URL-s look nice and work.
- Rendering is slightly different as well

The changes are here:
https://github.com/rackt/react-router/blob/master/UPGRADE_GUIDE.md

But they might not be so obvious for everyone to change themselves, I've spent hours making those changes, since I don't even fully understand the previous version and replacing one line with another according to the upgrade guide didn't really work.

**Comment by adamarthurryan** [comment]
Hi @sergonius, 

I had to do some work upgrading to react-router 1.0 recently too, so I know what you mean. 

However, at the moment, we're only creating patches that (a) fix a mistake or bug in the code, or (b) are made by the instructor to improve the tutorial or course. The thinking is that we want to maintain the correspondence between the source repositories and the course videos as much as possible.

It would be interesting to be able to share the results of your work with other users though. What about posting a link to your fork and the list of changes you've made to the [Student Forum](https://community.tutsplus.com/c/student-forum)?
